# Permalinks
permalink:           pretty

# Setup
title:               Brian Z. OToole
tagline:             #
url:                 http://127.0.0.1:4000
produrl:             https://brianzotoole.com
paginate:            1
baseurl:             ""

# Assets
# Specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Brian OToole
  url:               https://twitter.com/brianotoole
  #email:             

# Custom vars
version:             1.0.0
github:
  url: https://brianotoole.github.io/brianz3/
 
collections:
  projects:
    output: true     

# Gems
gems:
  - jekyll-paginate
  - jekyll-assets
  - autoprefixer-rails
 # - jekyll-gist
 
# Jekyll-assets
assets:
  compress:
    css: true
    js: true
   
    
  #
  autowrite: true
  cache: false
  #cache_type: memory | filesystem | default: filesystem
  #cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: false

  #
  assets:
    - "*.png"
    - "bundle.css"

  #
  sources:
    - _assets/css
    - _assets/images
    - _assets/img
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/js

# Autoprefixer-rails
autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
