# Permalinks
permalink:           pretty

# Setup
title:               Brian Z. OToole
tagline:             #
url:                 127.0.0.1:4000
paginate:            1
baseurl:             ""

# Assets
# Specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Brian OToole
  url:               https://twitter.com/brianotoole
  #email:             

# Custom vars
version:             1.0.0
#github:
 #repo:             

# Gems
gems:
  - jekyll-paginate
 # - jekyll-gist
