# Setup
title:               Brian Z. OToole
tagline:             Create. Innovate. Inspire.
url:                 http://127.0.0.1:4000
produrl:             https://brianzotoole.com
paginate:            1
baseurl:             ""

# Permalinks
permalink:           pretty

# Assets
# Specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Brian OToole
  url:               https://twitter.com/brianotoole
  #email:

# Custom vars
version:             1.0.0
github:
  url: https://brianotoole.github.io/brianz3/

collections:
  projects:
    output: true

# Gems
gems:
  - jekyll-paginate
 # - jekyll-assets
 # - autoprefixer-rails
 # - jekyll-gist
