# Permalinks
permalink:           pretty

# Setup
title:               Brian Z. OToole
tagline:             #
url:                 127.0.0.1:4000
paginate:            1
baseurl:             ""

# Assets
# Specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Brian OToole
  url:               https://twitter.com/brianotoole
  #email:             

# Custom vars
version:             1.0.0
#github:
 #repo:             

# Gems
gems:
  - jekyll-paginate
  - jekyll-assets
  - autoprefixer-rails
 # - jekyll-gist
 
# Jekyll-assets
assets:
  compress:
    css: true
    js: true
    
  #
  autowrite: true
  cache: false
  #cache_type: memory | filesystem | default: filesystem
  #cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  #
  assets:
    - "*.png"
    - "bundle.css"

  #
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js

  #
  #features:
    #liquid: true | false | default: false
    #integrity: true | false | default: false
    #automatic_img_size: true | false | n(fixnum): 2,4,6,8 | default: true
    #automatic_img_alt : true | false | default: true
